name: Deploy

on:
  push:
    branches: [main]

# a workflow  run is made up of one or more jobs that run sequentially unless told otherwise
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #actions checkout is prebuilt actions
      # checks=out your rep under $GITHUB_WORKSPACE, so our job can access it
      - uses: actions/checkout@master
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          timeout: 300s
          source: "."
          target: "~/Discord"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies from requirements.txt
        run: |
          pipenv install -r ~/Discord/requirements.txt
      - name: Execute commands to start bot
        run: |
          pipenv run python launcher.py
